import XCTest
import Foundation
import DNSCore
@testable import DNSTypes

/// Differential test against the real `miekg/dns` library. `oracle.json` is
/// generated by `go run ./oracle` and holds the wire bytes (compression off)
/// that Go produces for each record below. Swift must produce identical bytes.
final class DifferentialTests: XCTestCase {
    private func hdr(_ type: RRType) -> RRHeader {
        RRHeader(name: Name("example.com."), type: type, class: .in, ttl: 300)
    }
    private func bytes(_ n: Int) -> [UInt8] { (0..<n).map { UInt8($0) } }

    /// Each case builds the same record the Go oracle built, keyed by name.
    private func makeRecords() -> [String: any RR] {
        [
            "A": A(header: hdr(.a), a: IPv4Address("192.0.2.1")),
            "AAAA": AAAA(header: hdr(.aaaa), aaaa: IPv6Address("2001:db8::1")),
            "MX": MX(header: hdr(.mx), preference: 10, mx: Name("mail.example.com.")),
            "NS": NS(header: hdr(.ns), ns: Name("ns1.example.com.")),
            "CNAME": CNAME(header: hdr(.cname), target: Name("target.example.com.")),
            "SOA": SOA(header: hdr(.soa), ns: Name("ns1.example.com."), mbox: Name("hostmaster.example.com."),
                       serial: 2024010101, refresh: 7200, retry: 3600, expire: 1209600, minttl: 3600),
            "SRV": SRV(header: hdr(.srv), priority: 1, weight: 5, port: 8080, target: Name("svc.example.com.")),
            "TXT": TXT(header: hdr(.txt), txt: ["hello", "world"]),
            "HINFO": HINFO(header: hdr(.hinfo), cpu: "Intel", os: "Linux"),
            "NAPTR": NAPTR(header: hdr(.naptr), order: 100, preference: 10, flags: "U",
                           service: "E2U+sip", regexp: "!^.*$!sip:x@y!", replacement: Name(".")),
            "CAA": CAA(header: hdr(.caa), flag: 0, tag: "issue", value: "letsencrypt.org"),
            "URI": URI(header: hdr(.uri), priority: 10, weight: 1, target: "https://example.com/path"),
            "LOC": LOC(header: hdr(.loc), version: 0, size: 0x33, horizPre: 0x16, vertPre: 0x13,
                       latitude: 2147483648, longitude: 2147483648, altitude: 10000000),
            "EUI48": EUI48(header: hdr(.eui48), address: 0x0011_2233_4455),
            "EUI64": EUI64(header: hdr(.eui64), address: 0x0011_2233_4455_6677),
            "NID": NID(header: hdr(.nid), preference: 10, nodeID: 0xABCD_1234_5678_9F00),
            "L64": L64(header: hdr(.l64), preference: 10, locator64: 0x0011_2233_4455_6677),
            "DS": DS(header: hdr(.ds), keyTag: 12345, algorithm: 8, digestType: 2, digest: [0xAB, 0xCD, 0xEF]),
            "DNSKEY": DNSKEY(header: hdr(.dnskey), flags: 256, proto: 3, algorithm: 8, publicKey: bytes(40)),
            "RRSIG": RRSIG(header: hdr(.rrsig), typeCovered: RRType.a.rawValue, algorithm: 8, labels: 2,
                           origTtl: 3600, expiration: 1700000000, inception: 1699000000, keyTag: 54321,
                           signerName: Name("example.com."), signature: bytes(64)),
            "TLSA": TLSA(header: hdr(.tlsa), usage: 3, selector: 1, matchingType: 1, certificate: bytes(32)),
            "CERT": CERT(header: hdr(.cert), type: 1, keyTag: 1234, algorithm: 8, certificate: bytes(20)),
            "NSEC": NSEC(header: hdr(.nsec), nextDomain: Name("next.example.com."),
                         typeBitMap: [RRType.a.rawValue, RRType.mx.rawValue, RRType.rrsig.rawValue, RRType.nsec.rawValue]),
            "CSYNC": CSYNC(header: hdr(.csync), serial: 66, flags: 3,
                           typeBitMap: [RRType.a.rawValue, RRType.ns.rawValue, RRType.aaaa.rawValue]),
            "TKEY": TKEY(header: hdr(.tkey), algorithm: Name("hmac-sha256."), inception: 1, expiration: 2,
                         mode: 3, error: 0, keySize: 16, key: bytes(16), otherLen: 2, otherData: [0xFF, 0xEE]),
            "OPT": OPT(udpSize: 1232, dnssecOK: true, options: [
                EDNS0_NSID(nsid: [0xAA, 0xBB]),
                EDNS0_COOKIE(cookie: bytes(8)),
                EDNS0_EDE(infoCode: 6, extraText: "bad"),
                EDNS0_PADDING(padding: [0, 0, 0, 0]),
                EDNS0_SUBNET(family: 1, sourceNetmask: 24, sourceScope: 0, address: [192, 0, 2]),
                EDNS0_TCP_KEEPALIVE(timeout: 100),
                EDNS0_EXPIRE(expire: 86400),
            ]),
            "SVCB": SVCB(header: hdr(.svcb), priority: 1, target: Name("svc.example.com."), values: [
                SVCBMandatory(codes: [SVCBKey.alpn, SVCBKey.ipv4hint]),
                SVCBAlpn(alpn: ["h2", "h3"]),
                SVCBPort(port: 443),
                SVCBIPv4Hint(hints: [IPv4Address("192.0.2.1"), IPv4Address("192.0.2.2")]),
                SVCBECHConfig(ech: [0xAB, 0xCD]),
                SVCBIPv6Hint(hints: [IPv6Address("2001:db8::1")]),
                SVCBDoHPath(template: "/dns-query{?dns}"),
                SVCBLocal(key: 65280, data: Array("xyz".utf8)),
            ]),
            "HTTPS": HTTPS(header: hdr(.https), priority: 0, target: Name("."), values: [
                SVCBAlpn(alpn: ["h3"]),
            ]),
        ]
    }

    func testMatchesGoOracle() throws {
        let jsonURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().appendingPathComponent("oracle.json")
        let data = try Data(contentsOf: jsonURL)
        let expected = try JSONSerialization.jsonObject(with: data) as! [String: String]
        XCTAssertFalse(expected.isEmpty, "oracle.json is empty")

        let records = makeRecords()
        // Every oracle vector must have a matching Swift record and identical bytes.
        for (name, expectedHex) in expected.sorted(by: { $0.key < $1.key }) {
            guard let rr = records[name] else {
                XCTFail("no Swift record built for oracle case '\(name)'")
                continue
            }
            let got = try rr.packedBytes(compress: false).map { String(format: "%02x", $0) }.joined()
            XCTAssertEqual(got, expectedHex, "wire mismatch vs miekg/dns for \(name)")
        }
    }
}
